### ISSUE TITLE
edgeconnect-telemetry-demo issue

### ISSUE THREAD

**Issue by hopoffbaby** [aruba/pyedgeconnect#10]
Hi,

I am trying to run the edgeconnect-telemetry-demo.

All the services start, but it seems that the  ec-telemetry-ec-telemetry-worker-[1-4] processes are having trouble writing to influxdb:

`
Process MultiprocessingWriter-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.10/dist-packages/influxdb_client/client/util/multiprocessing_helper.py", line 164, in run
    self.write_api.write(**next_record)
  File "/usr/local/lib/python3.10/dist-packages/influxdb_client/client/write_api.py", line 353, in write
    return self._write_batching(bucket, org, record,
  File "/usr/local/lib/python3.10/dist-packages/influxdb_client/client/write_api.py", line 445, in _write_batching
    self._write_batching(bucket, org, item, precision, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/influxdb_client/client/write_api.py", line 426, in _write_batching
    self._write_batching(bucket, org, Point.from_dict(data, write_precision=precision, **kwargs),
  File "/usr/local/lib/python3.10/dist-packages/influxdb_client/client/write_api.py", line 423, in _write_batching
    self._write_batching(bucket, org, data.to_line_protocol(), data.write_precision, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/influxdb_client/client/write/point.py", line 185, in to_line_protocol
    _fields = _append_fields(self._fields)
  File "/usr/local/lib/python3.10/dist-packages/influxdb_client/client/write/point.py", line 247, in _append_fields
    raise ValueError(f'Type: "{type(value)}" of field: "{field}" is not supported.')
ValueError: Type: "<class 'dict'>" of field: "traffic_class_name" is not supported.
`

I have tried updating the docker-compose file to pin the container image versions to those detail in readthedocs, but I get the same issue.

I also had to change the following in example.env:

`
COMPOSE_PROJECT_NAME=ec-telemetry
`

as the mixed upper/lowercase name is not supported by docker-compose.

Any ideas on this one?

Thanks,

**Comment by adamwilkins-hpe** [comment]
Change was commited and merged to development branch.
